"""Character looks shared by the overworld sprites and the dialogue portraits.

Each entry describes one person once: skin, hair, outfit, hat, extras.
npcs.py draws them as 48x64 front-facing walkers, portraits.py as
160x200 busts, so the two always agree.
"""
from __future__ import annotations

SKIN = {"light": "#f0c8a4", "fair": "#f6d8c0", "tan": "#d8a478", "brown": "#a8724c", "dark": "#7a4e34",
        "pale": "#dcd4d0", "dead": "#b8c0c8"}

# keys: skin, hair, hair_style (short|long|bun|braid|bald|wild|pony|none), outfit (coat|robe|armor|dress|tunic|vest),
# main, trim, pants, boots, hat (none|cap|peaked|crown|hood|helmet|plume|wig), hat_col, beard (none|full|mustache|stubble|goatee),
# beard_col, eyes, extras (list of tags), age (young|adult|old), build (slim|avg|broad), expr (neutral|smile|frown|sad|smirk|shock|grim)
PEOPLE = {
    # ---- Weeping Army and the crown
    "weepingGuard": dict(skin="dead", hair="#3a3a40", hair_style="none", outfit="armor", main="#5a5c64", trim="#34363c",
                         pants="#3a3c42", boots="#26262c", hat="helmet", hat_col="#6a6c74", eyes="#9ad0ff",
                         extras=["tears", "spear"], expr="grim", build="avg"),
    "royalGuard": dict(skin="light", hair="#5a3a24", hair_style="short", outfit="armor", main="#7a2230", trim="#d8b048",
                       pants="#3a2a2a", boots="#2a1e1a", hat="plume", hat_col="#9aa0a8", plume="#c02a3a",
                       eyes="#3a2a1a", extras=["halberd", "tabard"], expr="frown", build="broad"),
    "nero": dict(skin="pale", hair="#18121e", hair_style="long", outfit="robe", main="#3c1446", trim="#e0b840",
                 pants="#24102a", boots="#1a0e1e", hat="crown", hat_col="#e8c040", eyes="#b02a3a",
                 extras=["tears", "cape", "fur_collar"], expr="grim", build="slim", age="adult"),
    # ---- nine Generals: officer uniform and peaked cap in their city color
    "harrow": dict(skin="tan", hair="#b8b0a8", hair_style="short", outfit="coat", main="#6e5434", trim="#d8b040",
                   pants="#3a2e22", boots="#241a14", hat="peaked", hat_col="#6e5434", beard="full", beard_col="#c8c0b8",
                   eyes="#3a2a1a", age="old", expr="grim", extras=["medals", "epaulets"], build="broad"),
    "ashgrove": dict(skin="fair", hair="#a88a4a", hair_style="short", outfit="coat", main="#686030", trim="#d8b040",
                     pants="#3a3620", boots="#241e14", hat="peaked", hat_col="#686030", eyes="#4a6a3a", age="young",
                     expr="shock", extras=["medals", "sweat"], build="slim"),
    "stroud": dict(skin="light", hair="#4a3a30", hair_style="bald", outfit="coat", main="#54466e", trim="#d8b040",
                   pants="#2e2640", boots="#1e1a26", hat="peaked", hat_col="#54466e", beard="stubble",
                   beard_col="#4a3a30", eyes="#3a2a1a", expr="frown", extras=["keys", "medals"], build="broad"),
    "vale": dict(skin="pale", hair="#101014", hair_style="short", outfit="coat", main="#2c2836", trim="#d8b040",
                 pants="#1a1820", boots="#101014", hat="peaked", hat_col="#2c2836", eyes="#6a6a80", expr="smile",
                 extras=["medals", "gloves"], build="slim"),
    "kessler": dict(skin="tan", hair="#6a2a1a", hair_style="short", outfit="coat", main="#782c24", trim="#d8b040",
                    pants="#3a1a16", boots="#241410", hat="peaked", hat_col="#782c24", beard="mustache",
                    beard_col="#6a2a1a", eyes="#e08030", expr="smirk", extras=["scar", "torch", "medals"], build="avg"),
    "morrow": dict(skin="brown", hair="#1a1410", hair_style="short", outfit="coat", main="#284676", trim="#d8b040",
                   pants="#1a2a44", boots="#141c2a", hat="peaked", hat_col="#284676", beard="goatee",
                   beard_col="#1a1410", eyes="#3a2a1a", expr="sad", extras=["flask", "medals"], build="avg"),
    "crane": dict(skin="fair", hair="#e8e8e8", hair_style="pony", outfit="coat", main="#96968f", trim="#d8b040",
                  pants="#56564f", boots="#2e2e2a", hat="peaked", hat_col="#96968f", eyes="#3a4a6a", age="old",
                  expr="neutral", extras=["bird", "medals"], build="slim"),
    "blackwood": dict(skin="dark", hair="#141010", hair_style="short", outfit="coat", main="#2e5632", trim="#d8b040",
                      pants="#1e3420", boots="#141a14", hat="peaked", hat_col="#2e5632", beard="full",
                      beard_col="#1a1410", eyes="#3a2a1a", expr="frown", extras=["patch", "medals", "epaulets"],
                      build="broad"),
    "sorrel": dict(skin="light", hair="#c87a3a", hair_style="braid", outfit="armor", main="#46549a", trim="#e6e6f0",
                   pants="#2a3060", boots="#1a1e34", hat="peaked", hat_col="#46549a", eyes="#3a5a8a", expr="grim",
                   extras=["cape", "sword", "medals", "epaulets"], build="broad"),
    # ---- Malkuth
    "ada": dict(skin="light", hair="#7a4a2a", hair_style="bun", outfit="coat", main="#e2e2d6", trim="#3c8c5a",
                pants="#5a6a5a", boots="#3a2e24", hat="none", eyes="#3a6a4a", expr="smile", extras=["satchel", "cross"]),
    "hale": dict(skin="tan", hair="#5a3a1e", hair_style="short", outfit="vest", main="#8c6032", trim="#5a3c1e",
                 shirt="#e8dcc0", pants="#4a3a2a", boots="#2a1e14", hat="cap", hat_col="#6a4a2a", beard="mustache",
                 beard_col="#5a3a1e", eyes="#3a2a1a", expr="smile", extras=["apron", "satchel"], build="broad"),
    "marn": dict(skin="tan", hair="#d0d0d0", hair_style="bald", outfit="robe", main="#605a6e", trim="#c8c8c8",
                 pants="#403a4a", boots="#2a2630", hat="hood", hat_col="#605a6e", beard="full", beard_col="#e0e0e0",
                 eyes="#4a4a5a", age="old", expr="neutral", extras=["staff"]),
    "citizen": dict(skin="light", hair="#6a4a2a", hair_style="short", outfit="tunic", main="#786e50", trim="#a08c64",
                    pants="#4a4234", boots="#2e2820", hat="none", eyes="#3a2a1a", expr="smile", extras=["belt"]),
    # ---- Ghost Guild arc
    "vesk": dict(skin="dead", hair="#101014", hair_style="long", outfit="robe", main="#222024", trim="#786e82",
                 pants="#18161a", boots="#101012", hat="hood", hat_col="#222024", eyes="#c8c0ff", expr="grim",
                 extras=["veil", "lantern", "tears"], build="slim"),
    "ghost": dict(skin="dead", hair="#9aa6c0", hair_style="none", outfit="ghost", main="#b8c8e2", trim="#8496bc",
                  pants="#b8c8e2", boots="#b8c8e2", hat="helmet", hat_col="#a6b4d0", eyes="#20283a", expr="sad",
                  extras=["tears"]),
    # ---- Heroes Guild (blue and silver)
    "ardent": dict(skin="light", hair="#e0c060", hair_style="short", outfit="armor", main="#2e4e9c", trim="#dcdce6",
                   pants="#243a70", boots="#2a2a36", hat="none", eyes="#3a6ab0", expr="smile",
                   extras=["cape", "sword", "epaulets"], build="broad"),
    "pell": dict(skin="brown", hair="#2a1a10", hair_style="short", outfit="tunic", main="#46649e", trim="#dcdce6",
                 pants="#2e3e60", boots="#2a2420", hat="cap", hat_col="#46649e", eyes="#3a2a1a", age="young",
                 expr="neutral", extras=["spear", "belt"]),
    "aldous": dict(skin="fair", hair="#c8a060", hair_style="wild", outfit="armor", main="#3c5a9e", trim="#d8b048",
                   pants="#2a3a66", boots="#2a2420", hat="plume", hat_col="#c0c4cc", plume="#3c5a9e", beard="mustache",
                   beard_col="#c8a060", eyes="#4a6a9a", expr="sad", extras=["sword", "tears"], build="avg"),
    "brin": dict(skin="tan", hair="#3a2418", hair_style="braid", outfit="armor", main="#34508e", trim="#d8b048",
                 pants="#24365e", boots="#2a2420", hat="none", eyes="#4a3a2a", expr="frown", extras=["sword", "cape"],
                 build="broad"),
    "rook": dict(skin="brown", hair="#18120e", hair_style="short", outfit="armor", main="#1e3c78", trim="#e6e6f0",
                 pants="#16284e", boots="#141824", hat="peaked", hat_col="#1e3c78", beard="stubble",
                 beard_col="#18120e", eyes="#2a2a3a", expr="grim", extras=["scar", "cape", "sword", "epaulets"],
                 build="broad"),
    # ---- Thieves Guild (dark with red) and outlaws
    "mag": dict(skin="tan", hair="#8a1e1e", hair_style="long", outfit="coat", main="#32202a", trim="#aa2828",
                pants="#22161c", boots="#140e10", hat="hood", hat_col="#32202a", eyes="#c89a3a", expr="smirk",
                extras=["eyepatch", "dagger", "belt"], build="avg"),
    "fingers": dict(skin="light", hair="#4a3222", hair_style="wild", outfit="vest", main="#463c32", trim="#aa2828",
                    shirt="#8a7a64", pants="#2e2620", boots="#1e1814", hat="cap", hat_col="#3a3028", eyes="#3a2a1a",
                    age="young", expr="smirk", extras=["gloves", "satchel"], build="slim"),
    "mallory": dict(skin="fair", hair="#c0301e", hair_style="long", outfit="coat", main="#962828", trim="#3c1e14",
                    pants="#3a2a1e", boots="#2a1a12", hat="hood", hat_col="#962828", eyes="#3a6a3a", expr="smirk",
                    extras=["bow", "belt"], build="slim"),
    "silas": dict(skin="light", hair="#5a4a3a", hair_style="short", outfit="coat", main="#5a503c", trim="#968240",
                  pants="#3a3428", boots="#241e18", hat="cap", hat_col="#463c2c", beard="goatee", beard_col="#5a4a3a",
                  eyes="#6a5a2a", expr="smirk", extras=["sack", "rings"], build="avg"),
    # ---- townsfolk archetypes
    "townsman": dict(skin="tan", hair="#5a3a22", hair_style="short", outfit="vest", main="#6e6046", trim="#50402a",
                     shirt="#dcd0b0", pants="#4a3e2c", boots="#2a2016", hat="cap", hat_col="#5a4a30", beard="stubble",
                     beard_col="#5a3a22", eyes="#3a2a1a", expr="neutral", extras=["belt"]),
    "townswoman": dict(skin="light", hair="#8a5a2a", hair_style="bun", outfit="dress", main="#965a6e", trim="#f0e6d6",
                       pants="#965a6e", boots="#3a2a20", hat="none", eyes="#4a6a3a", expr="smile", extras=["apron"]),
    "elder": dict(skin="fair", hair="#e2e2e2", hair_style="bald", outfit="robe", main="#787878", trim="#dcdcdc",
                  pants="#505050", boots="#302a26", hat="none", beard="full", beard_col="#ececec", eyes="#4a4a5a",
                  age="old", expr="smile", extras=["staff"]),
    "child": dict(skin="light", hair="#a8702e", hair_style="wild", outfit="tunic", main="#5a8c5a", trim="#7a502a",
                  pants="#4a3a2a", boots="#3a2a1e", hat="none", eyes="#3a2a1a", age="child", expr="smile",
                  extras=["belt"]),
    "bandit": dict(skin="tan", hair="#2a2018", hair_style="short", outfit="coat", main="#3c3228", trim="#8c2828",
                   pants="#2a221a", boots="#1a1410", hat="hood", hat_col="#3c3228", beard="stubble",
                   beard_col="#2a2018", eyes="#3a2a1a", expr="frown", extras=["mask", "dagger", "belt"]),
}

# ---- named townsfolk, house characters and rescued kids: each gets their own
# look instead of sharing the generic townsman/townswoman/elder/child art
PEOPLE.update({
    "crier": dict(skin="light", hair="#8a5a2a", hair_style="short", outfit="coat", main="#a8302a", trim="#e0c060",
                  pants="#3a2a22", boots="#2a1e16", hat="cap", hat_col="#2a3a6a", eyes="#3a2a1a", expr="shock",
                  extras=["satchel", "belt"], build="avg"),
    "tam": dict(skin="tan", hair="#d8d0c8", hair_style="bald", outfit="vest", main="#6a5a3a", trim="#c8a040",
                shirt="#d8ccb0", pants="#4a3e2e", boots="#2e241a", hat="none", beard="full", beard_col="#e0d8d0",
                eyes="#3a2a1a", age="old", expr="sad", extras=["keys"], build="slim"),
    "lina": dict(skin="fair", hair="#c8a060", hair_style="braid", outfit="dress", main="#5a8ab0", trim="#f0e8d8",
                 pants="#3a4a5a", boots="#4a3424", hat="none", eyes="#4a6a8a", expr="sad", extras=["apron"]),
    "rolo": dict(skin="fair", hair="#c89a50", hair_style="wild", outfit="tunic", main="#4a8a5a", trim="#e0d0a0",
                 pants="#5a4a32", boots="#3a2a1e", hat="none", eyes="#4a6a8a", age="child", expr="smile",
                 extras=["satchel"]),
    "juno": dict(skin="brown", hair="#2a1a14", hair_style="pony", outfit="coat", main="#3a6a6a", trim="#e0b060",
                 pants="#2e3a3a", boots="#2a201a", hat="none", eyes="#3a2a1a", expr="smile",
                 extras=["satchel", "gloves"], build="slim"),
    "bet": dict(skin="light", hair="#e8e4e0", hair_style="bun", outfit="dress", main="#6a4a6a", trim="#d8c8b8",
                pants="#3a2a3a", boots="#2a1e24", hat="none", eyes="#5a5a6a", age="old", expr="sad",
                extras=["cross", "apron"]),
    "pip": dict(skin="light", hair="#6a3a1e", hair_style="short", outfit="tunic", main="#b0702a", trim="#e8d8a8",
                pants="#4a3a28", boots="#2e2218", hat="cap", hat_col="#5a6a3a", eyes="#3a2a1a", age="child",
                expr="shock", extras=["sack"]),
    "cobb": dict(skin="tan", hair="#8a6a3a", hair_style="short", outfit="vest", main="#7a8a3a", trim="#4a3a22",
                 shirt="#e0d4b8", pants="#5a4a2a", boots="#3a2a1a", hat="cap", hat_col="#c8a860", beard="stubble",
                 beard_col="#8a6a3a", eyes="#3a2a1a", expr="frown", extras=["apron"], build="broad"),
    "sera": dict(skin="pale", hair="#2a2a30", hair_style="long", outfit="dress", main="#2a2a34", trim="#6a6a78",
                 pants="#1e1e24", boots="#18181c", hat="hood", hat_col="#2a2a34", eyes="#5a6a8a", expr="sad",
                 extras=["veil", "tears"]),
    "dunn": dict(skin="brown", hair="#1a1410", hair_style="short", outfit="coat", main="#4a5a3a", trim="#a8a8a0",
                 pants="#2e3424", boots="#1e2018", hat="helmet", hat_col="#6a6a62", beard="mustache",
                 beard_col="#1a1410", eyes="#3a2a1a", expr="frown", extras=["lantern", "belt"], build="avg"),
    "garrow": dict(skin="tan", hair="#6a2a1a", hair_style="wild", outfit="vest", main="#5a2a22", trim="#b8b0a0",
                   shirt="#3a2a22", pants="#2a1e18", boots="#1a1410", hat="none", beard="goatee", beard_col="#6a2a1a",
                   eyes="#c83020", expr="smirk", extras=["dagger", "scar", "rings", "belt"], build="slim"),
    "hesse": dict(skin="light", hair="#b85a2a", hair_style="bun", outfit="dress", main="#8a5a8a", trim="#f0e0c0",
                  pants="#4a2e4a", boots="#3a2420", hat="none", eyes="#3a6a3a", expr="shock", extras=["apron"]),
    "tilly": dict(skin="light", hair="#e0a050", hair_style="braid", outfit="dress", main="#e0a0b0", trim="#fff4e0",
                  pants="#8a5a6a", boots="#6a3a2a", hat="none", eyes="#3a6a3a", age="child", expr="smile",
                  extras=["satchel"]),
    "voss": dict(skin="fair", hair="#5a5a60", hair_style="short", outfit="coat", main="#6a4a2a", trim="#c8b070",
                 pants="#3a2a1e", boots="#2a1e16", hat="none", beard="goatee", beard_col="#6a6a70", eyes="#3a4a6a",
                 expr="smirk", extras=["satchel", "gloves", "rings"], build="slim"),
    "lune": dict(skin="tan", hair="#a0a0a8", hair_style="pony", outfit="robe", main="#3a5a7a", trim="#e0c060",
                 pants="#24384c", boots="#1e2a38", hat="none", eyes="#6a8aa8", age="old", expr="neutral",
                 extras=["satchel", "staff"], build="slim"),
    "holt": dict(skin="light", hair="#7a5a3a", hair_style="short", outfit="armor", main="#4a5a4a", trim="#b0a070",
                 pants="#2e3a2e", boots="#1e241e", hat="none", beard="full", beard_col="#7a5a3a", eyes="#3a2a1a",
                 expr="grim", extras=["sword", "epaulets", "scar"], build="broad"),
    "kael": dict(skin="brown", hair="#101010", hair_style="long", outfit="armor", main="#2e3a2e", trim="#6a2a2a",
                 pants="#1e241e", boots="#141814", hat="none", beard="stubble", beard_col="#101010", eyes="#b0a060",
                 expr="smirk", extras=["eyepatch", "sword", "cape"], build="avg"),
    "anselm": dict(skin="fair", hair="#8a7a6a", hair_style="bald", outfit="robe", main="#6a5a44", trim="#e8dcc0",
                   pants="#3a3226", boots="#2a2218", hat="none", eyes="#4a5a3a", age="old", expr="neutral",
                   extras=["cross", "belt"], build="avg"),
    "iona": dict(skin="light", hair="#3a2a20", hair_style="none", outfit="robe", main="#e8e4dc", trim="#4a6a9a",
                 pants="#a8a49c", boots="#5a5048", hat="hood", hat_col="#2a3a5a", eyes="#4a6a9a", expr="smile",
                 extras=["cross"], build="slim"),
    "rhee": dict(skin="tan", hair="#e0dcd8", hair_style="long", outfit="robe", main="#5a2a4a", trim="#e0c060",
                 pants="#3a1a30", boots="#241420", hat="none", beard="full", beard_col="#e8e4e0", eyes="#3a2a1a",
                 age="old", expr="neutral", extras=["staff", "rings"], build="slim"),
    "wyn": dict(skin="fair", hair="#b0b0b8", hair_style="bun", outfit="robe", main="#3a4a3a", trim="#c8b070",
                pants="#26302a", boots="#1e221e", hat="none", eyes="#4a5a4a", age="old", expr="frown",
                extras=["keys", "lantern"], build="slim"),
    "lark": dict(skin="brown", hair="#2a1a10", hair_style="wild", outfit="vest", main="#8a6a3a", trim="#4a3a2a",
                 shirt="#e8dcc0", pants="#3a3226", boots="#2a2018", hat="none", eyes="#3a2a1a", age="young",
                 expr="smile", extras=["satchel"], build="slim"),
    "hollis": dict(skin="tan", hair="#8a3a1e", hair_style="bun", outfit="dress", main="#7a3a2a", trim="#e8d8b8",
                   pants="#4a2a1e", boots="#2e1e16", hat="none", eyes="#3a2a1a", expr="smirk",
                   extras=["apron", "keys"], build="broad"),
    "quill": dict(skin="light", hair="#4a3a2a", hair_style="long", outfit="coat", main="#4a4a6a", trim="#c8a040",
                  pants="#2a2a3a", boots="#3a2a1e", hat="hood", hat_col="#5a4a3a", beard="stubble", beard_col="#4a3a2a",
                  eyes="#6a8a5a", expr="smirk", extras=["satchel", "staff"], build="slim"),
    "brann": dict(skin="dark", hair="#d0ccc8", hair_style="short", outfit="vest", main="#5a4a3a", trim="#8a2a2a",
                  shirt="#b8ac98", pants="#3a2e24", boots="#2a2018", hat="none", beard="full", beard_col="#d8d4d0",
                  eyes="#3a2a1a", age="old", expr="frown", extras=["scar", "flask"], build="broad"),
    "osk": dict(skin="tan", hair="#8a8a80", hair_style="wild", outfit="robe", main="#5a5a3a", trim="#3a3a24",
                pants="#3a3a26", boots="#2a2a1a", hat="none", beard="full", beard_col="#9a9a90", eyes="#6a7a4a",
                age="old", expr="smirk", extras=["staff", "sack"], build="slim"),
    "ilse": dict(skin="fair", hair="#e8e0f0", hair_style="long", outfit="robe", main="#4a3a6a", trim="#c8b8e8",
                 pants="#2e2440", boots="#1e182a", hat="none", eyes="#8a6ab8", age="old", expr="smile",
                 extras=["staff", "rings", "fur_collar"], build="slim"),
    "maren": dict(skin="dead", hair="#c8d4e0", hair_style="long", outfit="ghost", main="#b8c8d8", trim="#e8f0f8",
                  pants="#a0b0c0", boots="#90a0b0", hat="none", eyes="#e0f0ff", age="child", expr="sad",
                  extras=["tears"]),
})
