"""Character looks shared by the overworld sprites and the dialogue portraits.

Each entry describes one person once: skin, hair, outfit, hat, extras.
npcs.py draws them as 48x64 front-facing walkers, portraits.py as
160x200 busts, so the two always agree.
"""
from __future__ import annotations

SKIN = {"light": "#f0c8a4", "fair": "#f6d8c0", "tan": "#d8a478", "brown": "#a8724c", "dark": "#7a4e34",
        "pale": "#dcd4d0", "dead": "#b8c0c8"}

# keys: skin, hair, hair_style (short|long|bun|braid|bald|wild|pony|none), outfit (coat|robe|armor|dress|tunic|vest),
# main, trim, pants, boots, hat (none|cap|peaked|crown|hood|helmet|plume|wig), hat_col, beard (none|full|mustache|stubble|goatee),
# beard_col, eyes, extras (list of tags), age (young|adult|old), build (slim|avg|broad), expr (neutral|smile|frown|sad|smirk|shock|grim)
PEOPLE = {
    # ---- Weeping Army and the crown
    "weepingGuard": dict(skin="dead", hair="#3a3a40", hair_style="none", outfit="armor", main="#5a5c64", trim="#34363c",
                         pants="#3a3c42", boots="#26262c", hat="helmet", hat_col="#6a6c74", eyes="#9ad0ff",
                         extras=["tears", "spear"], expr="grim", build="avg"),
    "royalGuard": dict(skin="light", hair="#5a3a24", hair_style="short", outfit="armor", main="#7a2230", trim="#d8b048",
                       pants="#3a2a2a", boots="#2a1e1a", hat="plume", hat_col="#9aa0a8", plume="#c02a3a",
                       eyes="#3a2a1a", extras=["halberd", "tabard"], expr="frown", build="broad"),
    "nero": dict(skin="pale", hair="#18121e", hair_style="long", outfit="robe", main="#3c1446", trim="#e0b840",
                 pants="#24102a", boots="#1a0e1e", hat="crown", hat_col="#e8c040", eyes="#b02a3a",
                 extras=["tears", "cape", "fur_collar"], expr="grim", build="slim", age="adult"),
    # ---- nine Generals: officer uniform and peaked cap in their city color
    "harrow": dict(skin="tan", hair="#b8b0a8", hair_style="short", outfit="coat", main="#6e5434", trim="#d8b040",
                   pants="#3a2e22", boots="#241a14", hat="peaked", hat_col="#6e5434", beard="full", beard_col="#c8c0b8",
                   eyes="#3a2a1a", age="old", expr="grim", extras=["medals", "epaulets"], build="broad"),
    "ashgrove": dict(skin="fair", hair="#a88a4a", hair_style="short", outfit="coat", main="#686030", trim="#d8b040",
                     pants="#3a3620", boots="#241e14", hat="peaked", hat_col="#686030", eyes="#4a6a3a", age="young",
                     expr="shock", extras=["medals", "sweat"], build="slim"),
    "stroud": dict(skin="light", hair="#4a3a30", hair_style="bald", outfit="coat", main="#54466e", trim="#d8b040",
                   pants="#2e2640", boots="#1e1a26", hat="peaked", hat_col="#54466e", beard="stubble",
                   beard_col="#4a3a30", eyes="#3a2a1a", expr="frown", extras=["keys", "medals"], build="broad"),
    "vale": dict(skin="pale", hair="#101014", hair_style="short", outfit="coat", main="#2c2836", trim="#d8b040",
                 pants="#1a1820", boots="#101014", hat="peaked", hat_col="#2c2836", eyes="#6a6a80", expr="smile",
                 extras=["medals", "gloves"], build="slim"),
    "kessler": dict(skin="tan", hair="#6a2a1a", hair_style="short", outfit="coat", main="#782c24", trim="#d8b040",
                    pants="#3a1a16", boots="#241410", hat="peaked", hat_col="#782c24", beard="mustache",
                    beard_col="#6a2a1a", eyes="#e08030", expr="smirk", extras=["scar", "torch", "medals"], build="avg"),
    "morrow": dict(skin="brown", hair="#1a1410", hair_style="short", outfit="coat", main="#284676", trim="#d8b040",
                   pants="#1a2a44", boots="#141c2a", hat="peaked", hat_col="#284676", beard="goatee",
                   beard_col="#1a1410", eyes="#3a2a1a", expr="sad", extras=["flask", "medals"], build="avg"),
    "crane": dict(skin="fair", hair="#e8e8e8", hair_style="pony", outfit="coat", main="#96968f", trim="#d8b040",
                  pants="#56564f", boots="#2e2e2a", hat="peaked", hat_col="#96968f", eyes="#3a4a6a", age="old",
                  expr="neutral", extras=["bird", "medals"], build="slim"),
    "blackwood": dict(skin="dark", hair="#141010", hair_style="short", outfit="coat", main="#2e5632", trim="#d8b040",
                      pants="#1e3420", boots="#141a14", hat="peaked", hat_col="#2e5632", beard="full",
                      beard_col="#1a1410", eyes="#3a2a1a", expr="frown", extras=["patch", "medals", "epaulets"],
                      build="broad"),
    "sorrel": dict(skin="light", hair="#c87a3a", hair_style="braid", outfit="armor", main="#46549a", trim="#e6e6f0",
                   pants="#2a3060", boots="#1a1e34", hat="peaked", hat_col="#46549a", eyes="#3a5a8a", expr="grim",
                   extras=["cape", "sword", "medals", "epaulets"], build="broad"),
    # ---- Malkuth
    "ada": dict(skin="light", hair="#7a4a2a", hair_style="bun", outfit="coat", main="#e2e2d6", trim="#3c8c5a",
                pants="#5a6a5a", boots="#3a2e24", hat="none", eyes="#3a6a4a", expr="smile", extras=["satchel", "cross"]),
    "hale": dict(skin="tan", hair="#5a3a1e", hair_style="short", outfit="vest", main="#8c6032", trim="#5a3c1e",
                 shirt="#e8dcc0", pants="#4a3a2a", boots="#2a1e14", hat="cap", hat_col="#6a4a2a", beard="mustache",
                 beard_col="#5a3a1e", eyes="#3a2a1a", expr="smile", extras=["apron", "satchel"], build="broad"),
    "marn": dict(skin="tan", hair="#d0d0d0", hair_style="bald", outfit="robe", main="#605a6e", trim="#c8c8c8",
                 pants="#403a4a", boots="#2a2630", hat="hood", hat_col="#605a6e", beard="full", beard_col="#e0e0e0",
                 eyes="#4a4a5a", age="old", expr="neutral", extras=["staff"]),
    "citizen": dict(skin="light", hair="#6a4a2a", hair_style="short", outfit="tunic", main="#786e50", trim="#a08c64",
                    pants="#4a4234", boots="#2e2820", hat="none", eyes="#3a2a1a", expr="smile", extras=["belt"]),
    # ---- Ghost Guild arc
    "vesk": dict(skin="dead", hair="#101014", hair_style="long", outfit="robe", main="#222024", trim="#786e82",
                 pants="#18161a", boots="#101012", hat="hood", hat_col="#222024", eyes="#c8c0ff", expr="grim",
                 extras=["veil", "lantern", "tears"], build="slim"),
    "ghost": dict(skin="dead", hair="#9aa6c0", hair_style="none", outfit="ghost", main="#b8c8e2", trim="#8496bc",
                  pants="#b8c8e2", boots="#b8c8e2", hat="helmet", hat_col="#a6b4d0", eyes="#20283a", expr="sad",
                  extras=["tears"]),
    # ---- Heroes Guild (blue and silver)
    "ardent": dict(skin="light", hair="#e0c060", hair_style="short", outfit="armor", main="#2e4e9c", trim="#dcdce6",
                   pants="#243a70", boots="#2a2a36", hat="none", eyes="#3a6ab0", expr="smile",
                   extras=["cape", "sword", "epaulets"], build="broad"),
    "pell": dict(skin="brown", hair="#2a1a10", hair_style="short", outfit="tunic", main="#46649e", trim="#dcdce6",
                 pants="#2e3e60", boots="#2a2420", hat="cap", hat_col="#46649e", eyes="#3a2a1a", age="young",
                 expr="neutral", extras=["spear", "belt"]),
    "aldous": dict(skin="fair", hair="#c8a060", hair_style="wild", outfit="armor", main="#3c5a9e", trim="#d8b048",
                   pants="#2a3a66", boots="#2a2420", hat="plume", hat_col="#c0c4cc", plume="#3c5a9e", beard="mustache",
                   beard_col="#c8a060", eyes="#4a6a9a", expr="sad", extras=["sword", "tears"], build="avg"),
    "brin": dict(skin="tan", hair="#3a2418", hair_style="braid", outfit="armor", main="#34508e", trim="#d8b048",
                 pants="#24365e", boots="#2a2420", hat="none", eyes="#4a3a2a", expr="frown", extras=["sword", "cape"],
                 build="broad"),
    "rook": dict(skin="brown", hair="#18120e", hair_style="short", outfit="armor", main="#1e3c78", trim="#e6e6f0",
                 pants="#16284e", boots="#141824", hat="peaked", hat_col="#1e3c78", beard="stubble",
                 beard_col="#18120e", eyes="#2a2a3a", expr="grim", extras=["scar", "cape", "sword", "epaulets"],
                 build="broad"),
    # ---- Thieves Guild (dark with red) and outlaws
    "mag": dict(skin="tan", hair="#8a1e1e", hair_style="long", outfit="coat", main="#32202a", trim="#aa2828",
                pants="#22161c", boots="#140e10", hat="hood", hat_col="#32202a", eyes="#c89a3a", expr="smirk",
                extras=["eyepatch", "dagger", "belt"], build="avg"),
    "fingers": dict(skin="light", hair="#4a3222", hair_style="wild", outfit="vest", main="#463c32", trim="#aa2828",
                    shirt="#8a7a64", pants="#2e2620", boots="#1e1814", hat="cap", hat_col="#3a3028", eyes="#3a2a1a",
                    age="young", expr="smirk", extras=["gloves", "satchel"], build="slim"),
    "mallory": dict(skin="fair", hair="#c0301e", hair_style="long", outfit="coat", main="#962828", trim="#3c1e14",
                    pants="#3a2a1e", boots="#2a1a12", hat="hood", hat_col="#962828", eyes="#3a6a3a", expr="smirk",
                    extras=["bow", "belt"], build="slim"),
    "silas": dict(skin="light", hair="#5a4a3a", hair_style="short", outfit="coat", main="#5a503c", trim="#968240",
                  pants="#3a3428", boots="#241e18", hat="cap", hat_col="#463c2c", beard="goatee", beard_col="#5a4a3a",
                  eyes="#6a5a2a", expr="smirk", extras=["sack", "rings"], build="avg"),
    # ---- townsfolk archetypes
    "townsman": dict(skin="tan", hair="#5a3a22", hair_style="short", outfit="vest", main="#6e6046", trim="#50402a",
                     shirt="#dcd0b0", pants="#4a3e2c", boots="#2a2016", hat="cap", hat_col="#5a4a30", beard="stubble",
                     beard_col="#5a3a22", eyes="#3a2a1a", expr="neutral", extras=["belt"]),
    "townswoman": dict(skin="light", hair="#8a5a2a", hair_style="bun", outfit="dress", main="#965a6e", trim="#f0e6d6",
                       pants="#965a6e", boots="#3a2a20", hat="none", eyes="#4a6a3a", expr="smile", extras=["apron"]),
    "elder": dict(skin="fair", hair="#e2e2e2", hair_style="bald", outfit="robe", main="#787878", trim="#dcdcdc",
                  pants="#505050", boots="#302a26", hat="none", beard="full", beard_col="#ececec", eyes="#4a4a5a",
                  age="old", expr="smile", extras=["staff"]),
    "child": dict(skin="light", hair="#a8702e", hair_style="wild", outfit="tunic", main="#5a8c5a", trim="#7a502a",
                  pants="#4a3a2a", boots="#3a2a1e", hat="none", eyes="#3a2a1a", age="child", expr="smile",
                  extras=["belt"]),
    "bandit": dict(skin="tan", hair="#2a2018", hair_style="short", outfit="coat", main="#3c3228", trim="#8c2828",
                   pants="#2a221a", boots="#1a1410", hat="hood", hat_col="#3c3228", beard="stubble",
                   beard_col="#2a2018", eyes="#3a2a1a", expr="frown", extras=["mask", "dagger", "belt"]),
}
