#!/usr/bin/env python3
"""Run the full Sorrow County world/Town Map validation chain and produce
a single consolidated audit report.

Chain: generate Town Map -> validate world graph -> validate Town Map
projection -> validate progression requirements.

Usage: python3 tools/world_graph/run_full_audit.py
Writes: docs/generated/sorrow_county_validation_report.md
Exit code: 1 if any stage reports an error, 0 otherwise (warnings do not
fail the run).
"""

import datetime
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = ROOT / "docs" / "generated" / "sorrow_county_validation_report.md"


def run(cmd, cwd=ROOT):
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def main():
    stages = []

    code, out = run(["node", "tools/generate-town-map.mjs"])
    stages.append(("Generate Town Map (tools/generate-town-map.mjs)", code, out))

    code, out = run(["python3", "tools/world_graph/validate_world_graph.py"])
    stages.append(("World Graph Validation (validate_world_graph.py)", code, out))

    code, out = run(["python3", "tools/world_graph/validate_town_projection.py"])
    stages.append(("Town Map Projection Validation (validate_town_projection.py)", code, out))

    code, out = run(["python3", "tools/world_graph/validate_progression_requirements.py"])
    stages.append(("Progression Requirement Validation (validate_progression_requirements.py)", code, out))

    overall_ok = all(code == 0 for _, code, _ in stages)

    lines = []
    lines.append("# Sorrow County World/Town Map Validation Report")
    lines.append("")
    lines.append("Auto-generated by `tools/world_graph/run_full_audit.py`. Do not hand-edit —")
    lines.append("re-run the script to refresh after any world/Town Map change.")
    lines.append("")
    lines.append(f"Generated: {datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds')}")
    lines.append("")
    lines.append(f"**Overall: {'PASS' if overall_ok else 'FAIL'}**")
    lines.append("")
    lines.append("| Stage | Result |")
    lines.append("|---|---|")
    for name, code, _ in stages:
        lines.append(f"| {name} | {'OK' if code == 0 else 'FAIL'} |")
    lines.append("")

    for name, code, out in stages:
        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"Result: **{'OK' if code == 0 else 'FAIL'}**")
        lines.append("")
        lines.append("```")
        lines.append(out.strip() or "(no output)")
        lines.append("```")
        lines.append("")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n")

    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")
    print(f"Overall: {'PASS' if overall_ok else 'FAIL'}")
    return 0 if overall_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
