CREATE TABLE IF NOT EXISTS agents (
 id TEXT PRIMARY KEY,
 name TEXT NOT NULL,
 capabilities TEXT NOT NULL,
 task TEXT,
 last_seen TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS claims (
 path TEXT PRIMARY KEY,
 owner TEXT NOT NULL,
 purpose TEXT NOT NULL,
 expires TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 sender TEXT NOT NULL,
 recipient TEXT NOT NULL,
 message TEXT NOT NULL,
 created TEXT NOT NULL,
 read INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS decisions (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 topic TEXT NOT NULL,
 decision TEXT NOT NULL,
 rationale TEXT NOT NULL,
 created TEXT NOT NULL
);
